"""
Prepare and submit a SLURM array for the configurations generated by
config_generator.py.

This is the cluster counterpart of launcher.py. It creates the same output
layout and metadata files, then writes one JSON task per simulation and an
sbatch script that runs those tasks as a SLURM array.
"""

import argparse
import json
import subprocess
import sys
import time
from pathlib import Path

import pandas as pd

from config_generator import generate_configs
from launcher import (
    append_dynamic_index,
    build_command,
    collect_outputs,
    compile_executable,
    complete_config,
    existing_run_count,
    experiment_root,
    global_index_path,
    index_row,
    jsonable,
    metadata_config,
    prepare_run_dir,
    run_signature,
    write_json,
    write_run_network_config,
)


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--start-at", type=int, default=1)
    parser.add_argument("--stop-after", type=int, default=None)
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--continue-on-error", action="store_true")
    parser.add_argument("--no-submit", action="store_true")
    parser.add_argument(
        "--experiment-name",
        default=None,
        help="Optional output folder name. Defaults to exp_YYYYMMDD_HHMMSS.",
    )
    parser.add_argument(
        "--python",
        default=sys.executable,
        help="Python executable to use inside the sbatch script.",
    )
    parser.add_argument(
        "--run-task",
        default=None,
        help=argparse.SUPPRESS,
    )
    return parser.parse_args()


def task_summary(config, command):
    return {
        "global_run_number": config["global_run_number"],
        "run_number": config["run_number"],
        "experiment_id": config["experiment_id"],
        "experiment_dir": config["experiment_dir"],
        "run_dir": config["run_dir"],
        "command": command,
        "submitted_at": pd.Timestamp.now().isoformat(),
        "started_at": None,
        "finished_at": None,
        "returncode": None,
        "elapsed_seconds": None,
        "status": "submitted",
    }


def expected_output_paths(run_dir, config):
    outputs = {
        "results_path": str(run_dir / "results.csv"),
        "states_path": None,
        "weights_path": None,
    }
    if int(config["save_state"]) == 1:
        outputs["states_path"] = str(run_dir / "states.csv")
    if int(config["save_weights"]) == 1:
        outputs["weights_path"] = str(run_dir / "weights.csv")
    return outputs


def prepare_task(raw_config, global_run_number, run_number, root, exe_path, args):
    config = complete_config(raw_config, path_mode="cluster")
    run_dir = prepare_run_dir(root, run_number, config["net"], args.overwrite)
    config["experiment_id"] = root.name
    config["experiment_dir"] = str(root)
    config["global_run_number"] = global_run_number
    config["run_number"] = run_number
    config["run_dir"] = str(run_dir)

    saved_config = metadata_config(config)
    write_json(run_dir / "config.json", saved_config)
    write_run_network_config(run_dir.parent, saved_config)

    command, tmp_output_dir = build_command(config, run_dir, exe_path)
    summary = task_summary(config, command)
    write_json(run_dir / "summary.json", summary)

    return {
        "config": config,
        "saved_config": saved_config,
        "summary": summary,
        "command": command,
        "run_dir": str(run_dir),
        "tmp_output_dir": str(tmp_output_dir),
        "outputs": expected_output_paths(run_dir, config),
    }


def write_task(task, tasks_dir, task_number):
    task_path = tasks_dir / f"task_{task_number:06d}.json"
    write_json(task_path, task)
    return task_path


def write_manifest(task_paths, manifest_path):
    with manifest_path.open("w") as f:
        for path in task_paths:
            f.write(str(path) + "\n")


def write_sbatch(root, manifest_path, array_length, config, python_executable):
    slurm_dir = root / "slurm"
    slurm_dir.mkdir(parents=True, exist_ok=True)
    sbatch_path = root / "submit_array.sh"
    script_path = Path(__file__).resolve()
    max_jobs = int(config["max_jobs_simultaneous"])

    with sbatch_path.open("w") as f:
        f.write("#!/bin/bash -l\n")
        f.write(f"#SBATCH -J {config['jobname']}\n")
        f.write(f"#SBATCH --array=1-{array_length}%{max_jobs}\n")
        f.write("#SBATCH --ntasks=1\n")
        f.write("#SBATCH --cpus-per-task=2\n")
        f.write("#SBATCH --mem-per-cpu=1024M\n")
        f.write(f"#SBATCH --output={slurm_dir}/slurm-%A_%a.out\n")
        f.write("\n")
        f.write(f"manifest=\"{manifest_path}\"\n")
        f.write("task_file=$(sed -n \"${SLURM_ARRAY_TASK_ID}p\" \"$manifest\")\n")
        f.write("echo \"Running task ${SLURM_ARRAY_TASK_ID}: $task_file\"\n")
        f.write(f"srun \"{python_executable}\" \"{script_path}\" --run-task \"$task_file\"\n")

    return sbatch_path


def run_task(task_path):
    with Path(task_path).open() as f:
        task = json.load(f)

    run_dir = Path(task["run_dir"])
    tmp_output_dir = Path(task["tmp_output_dir"])
    config = task["config"]
    summary = task["summary"]
    command = task["command"]

    summary["status"] = "running"
    summary["started_at"] = pd.Timestamp.now().isoformat()
    write_json(run_dir / "summary.json", summary)

    start = time.perf_counter()
    proc = subprocess.run(command, capture_output=True, text=True)
    elapsed = time.perf_counter() - start

    with (run_dir / "log.txt").open("w") as log:
        log.write("$ " + " ".join(command) + "\n\n")
        log.write("STDOUT\n")
        log.write(proc.stdout)
        log.write("\nSTDERR\n")
        log.write(proc.stderr)

    summary["returncode"] = proc.returncode
    summary["elapsed_seconds"] = elapsed
    summary["finished_at"] = pd.Timestamp.now().isoformat()

    if proc.returncode != 0:
        summary["status"] = "failed"
        write_json(run_dir / "summary.json", summary)
        return proc.returncode

    outputs = collect_outputs(run_dir, tmp_output_dir, config)
    summary.update(outputs)
    summary["status"] = "completed"
    write_json(run_dir / "summary.json", summary)
    return 0


def main():
    args = parse_args()

    if args.run_task:
        return run_task(args.run_task)

    configs = generate_configs()
    if not configs:
        print("No configuration generated.")
        return 0

    first_config = complete_config(configs[0], path_mode="cluster")
    root = experiment_root(first_config, args.experiment_name)
    root.mkdir(parents=True, exist_ok=True)
    tasks_dir = root / "array_tasks"
    tasks_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = tasks_dir / "manifest.txt"
    index_path = root / "run_index.csv"
    global_index = global_index_path(first_config)

    print("Compiling executable...")
    exe_path = compile_executable(first_config)

    selected = configs[args.start_at - 1 :]
    if args.stop_after is not None:
        selected = selected[: args.stop_after]

    next_run_number = existing_run_count(root)
    run_numbers_by_signature = {}
    task_paths = []
    failures = 0

    for task_number, (offset, raw_config) in enumerate(
        enumerate(selected, start=args.start_at),
        start=1,
    ):
        try:
            config = complete_config(raw_config, path_mode="cluster")
            signature = run_signature(config, path_mode="cluster")
            if signature not in run_numbers_by_signature:
                next_run_number += 1
                run_numbers_by_signature[signature] = next_run_number
            run_number = run_numbers_by_signature[signature]

            task = prepare_task(
                config,
                offset,
                run_number,
                root,
                exe_path,
                args,
            )
            task_path = write_task(task, tasks_dir, task_number)
            task_paths.append(task_path)

            row = index_row(task["saved_config"], task["summary"], task["outputs"])
            append_dynamic_index(index_path, row)
            append_dynamic_index(global_index, row)
        except Exception as exc:
            failures += 1
            print(f"ERROR while preparing simulation {offset}: {exc}", file=sys.stderr)
            if not args.continue_on_error:
                return 1

    if not task_paths:
        print("No tasks prepared.")
        return 1

    write_manifest(task_paths, manifest_path)
    sbatch_path = write_sbatch(
        root,
        manifest_path,
        len(task_paths),
        first_config,
        args.python,
    )

    print(f"{len(task_paths)} array tasks prepared.")
    print(f"Experiment output: {root}")
    print(f"Index: {index_path}")
    print(f"Global index: {global_index}")
    print(f"SBATCH file: {sbatch_path}")
    print(f"Max simultaneous jobs: {int(first_config['max_jobs_simultaneous'])}")

    if args.no_submit:
        print("Not submitting because --no-submit was used.")
        return 0 if failures == 0 else 1

    proc = subprocess.run(["sbatch", str(sbatch_path)], capture_output=True, text=True)
    print(proc.stdout)
    if proc.stderr:
        print(proc.stderr, file=sys.stderr)
    return proc.returncode if proc.returncode != 0 else (0 if failures == 0 else 1)


if __name__ == "__main__":
    sys.exit(main())
